### ISSUE TITLE
Fix links to avatar on tweet timeline

### ISSUE THREAD

**Issue by Flixow** [hacklag/hacklag-website#103]
![image](https://cloud.githubusercontent.com/assets/17015114/19558721/54584ad6-96cc-11e6-99e0-42b558b8dfd3.png)

**Comment by kamilant** [comment]
@Flixow Do you use any kind of ad blocking addon?

**Comment by mkucharz** [comment]
@kamilant I think it may be related to http/https thing

**Comment by Flixow** [comment]
@kamilant Yes, I use something like this, but when I disabled it problem still persists. I've tried both http and https.
It looks like wrong url to image which leads to 404.

**Comment by kkkowalski** [comment]
We got a script, which is fetching data from Twitter into Syncano instance.
Looks like that after changing avatar on Twitter, link to image changed.
Atm I reloaded last Tweets and images seems to be working.

@Flixow Can you confirm that images are present on your devices?

**Comment by Flixow** [comment]
Yes, now it works properly

**Comment by kkkowalski** [comment]
Ok, I'll close it for now as resolved.
