### ISSUE TITLE
Design for map and contact info in footer

### ISSUE THREAD

**Issue by mkucharz** [hacklag/hacklag-website#105]

**Comment by Idered** [comment]
Design PSD file: [hacklag.zip](https://github.com/hacklag/hacklag-website/files/555438/hacklag.zip)

Preview:
![preview](https://cloud.githubusercontent.com/assets/230404/19762737/679607a4-9c3b-11e6-9372-92ad079a40fc.jpg)

**Comment by Idered** [comment]
@mkucharz Can you please add "Design" label? We should tag each issue properly.
